services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.4.5-0
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      # Certificate and key for HTTPS
      KC_HTTPS_CERTIFICATE_KEY_FILE: /opt/keycloak/conf/certs/keycloak.key.pem
      KC_HTTPS_CERTIFICATE_FILE: /opt/keycloak/conf/certs/keycloak.cert.pem
    ports:
      - "8080:8080"
      - "8443:8443"
    command:
      - start-dev
    user: "0"
    volumes:
      - keycloak_data:/opt/keycloak/data
      - ./certs:/opt/keycloak/conf/certs:ro
      - ./target/keycloak-scoutnet-authenticator-0.4.1-SNAPSHOT.jar:/opt/keycloak/providers/keycloak-scoutnet-authenticator-0.4.1-SNAPSHOT.jar
      - ./keycloak-theme-for-kc-all-other-versions.jar:/opt/keycloak/providers/keycloak-scoutid-theme.jar

volumes:
  keycloak_data: